# These are supported funding model platforms

github: [XiaoYangLiu-FinRL, BruceYanghy]
patreon: XiaoYangLiu_AI4Finance
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['paypal.me/AI4Finance', 'www.venmo.com/u/Xiao-Yang-Liu_AI4Finance']
